// Generated by gencpp from file catkin_startup/myserviceRequest.msg
// DO NOT EDIT!


#ifndef CATKIN_STARTUP_MESSAGE_MYSERVICEREQUEST_H
#define CATKIN_STARTUP_MESSAGE_MYSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace catkin_startup
{
template <class ContainerAllocator>
struct myserviceRequest_
{
  typedef myserviceRequest_<ContainerAllocator> Type;

  myserviceRequest_()
    : cmd()  {
    }
  myserviceRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _cmd_type;
  _cmd_type cmd;




  typedef boost::shared_ptr< ::catkin_startup::myserviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catkin_startup::myserviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct myserviceRequest_

typedef ::catkin_startup::myserviceRequest_<std::allocator<void> > myserviceRequest;

typedef boost::shared_ptr< ::catkin_startup::myserviceRequest > myserviceRequestPtr;
typedef boost::shared_ptr< ::catkin_startup::myserviceRequest const> myserviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::catkin_startup::myserviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::catkin_startup::myserviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace catkin_startup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'catkin_startup': ['/home/waxz/refloc_ws/src/catkin_startup/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::catkin_startup::myserviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::catkin_startup::myserviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::catkin_startup::myserviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "952a146467d5c456d42e02451e4b54fc";
  }

  static const char* value(const ::catkin_startup::myserviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x952a146467d5c456ULL;
  static const uint64_t static_value2 = 0xd42e02451e4b54fcULL;
};

template<class ContainerAllocator>
struct DataType< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "catkin_startup/myserviceRequest";
  }

  static const char* value(const ::catkin_startup::myserviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String cmd\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::catkin_startup::myserviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myserviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catkin_startup::myserviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::catkin_startup::myserviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CATKIN_STARTUP_MESSAGE_MYSERVICEREQUEST_H
