// Generated by gencpp from file catkin_startup/myservice.msg
// DO NOT EDIT!


#ifndef CATKIN_STARTUP_MESSAGE_MYSERVICE_H
#define CATKIN_STARTUP_MESSAGE_MYSERVICE_H

#include <ros/service_traits.h>


#include <catkin_startup/myserviceRequest.h>
#include <catkin_startup/myserviceResponse.h>


namespace catkin_startup
{

struct myservice
{

typedef myserviceRequest Request;
typedef myserviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myservice
} // namespace catkin_startup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::catkin_startup::myservice > {
  static const char* value()
  {
    return "d536dae086ffe923e1adaedf60a05f81";
  }

  static const char* value(const ::catkin_startup::myservice&) { return value(); }
};

template<>
struct DataType< ::catkin_startup::myservice > {
  static const char* value()
  {
    return "catkin_startup/myservice";
  }

  static const char* value(const ::catkin_startup::myservice&) { return value(); }
};


// service_traits::MD5Sum< ::catkin_startup::myserviceRequest> should match 
// service_traits::MD5Sum< ::catkin_startup::myservice > 
template<>
struct MD5Sum< ::catkin_startup::myserviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::catkin_startup::myservice >::value();
  }
  static const char* value(const ::catkin_startup::myserviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::catkin_startup::myserviceRequest> should match 
// service_traits::DataType< ::catkin_startup::myservice > 
template<>
struct DataType< ::catkin_startup::myserviceRequest>
{
  static const char* value()
  {
    return DataType< ::catkin_startup::myservice >::value();
  }
  static const char* value(const ::catkin_startup::myserviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::catkin_startup::myserviceResponse> should match 
// service_traits::MD5Sum< ::catkin_startup::myservice > 
template<>
struct MD5Sum< ::catkin_startup::myserviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::catkin_startup::myservice >::value();
  }
  static const char* value(const ::catkin_startup::myserviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::catkin_startup::myserviceResponse> should match 
// service_traits::DataType< ::catkin_startup::myservice > 
template<>
struct DataType< ::catkin_startup::myserviceResponse>
{
  static const char* value()
  {
    return DataType< ::catkin_startup::myservice >::value();
  }
  static const char* value(const ::catkin_startup::myserviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CATKIN_STARTUP_MESSAGE_MYSERVICE_H
